[default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz-runs = 100
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config